# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
on: [push, pull_request]
name: Run tests

jobs:
  tests:
    name: Tests

    strategy:
      matrix:
        # TODO add windows-latest
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Prepare java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@3.5
      with:
        cli: 1.10.3.998

    - name: Checkout
      uses: actions/checkout@v2

    - name: Poly check
      run: |
        clojure -M:poly check

    - name: tests
      run: |
        clojure -M:poly test
