# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
on: [push, pull_request]
name: Run tests

jobs:
  tests:
    name: Tests

    strategy:
      matrix:
        # TODO add windows-latest
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Prepare java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@10.3
      with:
        cli: 1.10.3.1029
         bb: 1.3.179

    - name: Checkout
      uses: actions/checkout@v2

    - name: check
      run: |
        set -x
        clojure -Srepro -M:poly check

    - name: test
      run: |
        set -x
        clojure -Srepro -M:poly test :all

    - name: build and install jar
      run: |
        set -x
        cd projects/makejack-jar
        clojure -T:build help | grep clean
        clojure -T:build help :target clean | grep clean
        clojure -T:build clean
        clojure -T:build jar
        clojure -T:build install

    - name: invoke
      run: |
        set -x
        ./mj help
